### ISSUE TITLE
Giving Credit

### ISSUE THREAD

**Issue by Infinite-Blue-1042** [AarinDave/AarinDave#1]
You used the Graph on contributions and the bar chart about most used languages, can you give credit from where that source came from? I started with me, then I passed down to @Aarav Dave. Thanks fellow Githuber!

**Comment by AarinDave** [comment]
Technically, there is no need to give credit since it is readily available using the Github API. Furthermore, you and @AaravDave took it from profiles with the best profile READMEs without credit. Thus, I would find it unnecessary. Thanks for noting the issue though.

**Comment by Infinite-Blue-1042** [comment]
OK, thanks for the response.

**Comment by AarinDave** [comment]
You're welcome. ;)
